# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: double_pinyin_flypy

switcher:
  caption: 〔方案〕
  hotkeys:
    - Control+grave

  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    # - zh_hant_tw
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 4

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
#  - {accept: "Control+space", toggle: "ascii_mode", when: always} # 中英文切换
  - {accept: "Shift+space", toggle: full_shape, when: always} # 全角半角转换
  - {accept: "Control+period", toggle: ascii_punct, when: always} # ctrl+. 切换中英文标点
  - {accept: minus, send: Page_Up, when: has_menu}
  - {accept: equal, send: Page_Down, when: has_menu}

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_code
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: commit_code
    # Eisu_toggle: clear

style:
  cursor_type: insert
  horizontal: true
  inline_preedit: true
  preedit_style: composition
