#!/usr/bin/env bash

iDIR="$HOME/.config/waybar/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
	echo "${LIGHT}%"
}

# Increase brightness
inc_backlight() {
	brightnessctl -d amdgpu_bl1 set 10%+
}
f
# Decrease brightness
dec_backlight() {
	brightnessctl -d amdgpu_bl1 set 10%- 
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
